sudo: required
language: android
dist: xenial
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-29.0.0
  - android-29
  - extra
before_install:
- openssl aes-256-cbc -K $encrypted_3d4ec2806c82_key -iv $encrypted_3d4ec2806c82_iv
  -in volatile_keystore.jks.enc -out volatile_keystore.jks -d
- chmod -R 777 ${HOME}
script:
- "./gradlew clean build check"
before_deploy:
- cp volatile_keystore.jks app/build/outputs/apk/release/volatile_keystore.jks
- cd app/build/outputs/apk/release
- ls
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore volatile_keystore.jks
  -storepass $storepass -keypass $storepass app-release-unsigned.apk authenticator
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/29.0.0/zipalign -v 4 app-release-unsigned.apk Authenticator.apk"
- ls
deploy:
  provider: releases
  file: Authenticator.apk
  skip_cleanup: true
  on:
    repo: siddhantvinchurkar/authenticator
    tags: true
  api_key: "$gak"
after_deploy:
- echo "App Successfully Deployed!"
